# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 10999434053c462f0ef02e98771753f3cf2d19233a59c07b43d99ca57d49bdb5bd2a2a50e2f1335bee2f80e1d6a4bd639d410418ad15f31463c397c7e06d7567

test:
  secret_key_base: c9a7c5c44ed746a361c5e4f2ef406afdf1171e932d5f451a0147a7710ed6a298fc7e01f9877021f90001a4507631eec21825e77b393fd6787265c87f0cf18dc3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
